[project]
name = "local-live-transcribe"
version = "0.1.0"
description = "A project for live transcription services"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "faster-whisper>=1.1.1",
    "numpy>=2.2.4",
    "pyaudio>=0.2.14",
]
